name: Run the ARGprofiler workflow
run-name: ${{ github.actor }} is testing out ARGprofiler ğŸš€
on: [push]
jobs:
  Run-the-ARGprofiler-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Do we have time?
        run: | 
          which time
          /usr/bin/time -v echo "hello"
      - name: Snakemake workflow dryrun
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '-np'
          stagein: ''
      - name: Snakemake test panres
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--use-conda --cores 1 --until fetch_db_panres_fa'
          stagein: ''
#      - name: Snakemake workflow full run
#        uses: snakemake/snakemake-github-action@v1.25.1
#        with:
#          directory: '.'
#          snakefile: 'Snakefile'
#          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'
#          stagein: '' # additional preliminary commands to run (can be multiline)
#          show-disk-usage-on-error: true
      - run: echo "ğŸ This job's status is ${{ job.status }}."
